apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: helloservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - helloservice.sample-app-production.20.204.253.86.nip.io
  - helloservice
  http:
  - route:
    - destination:
        host: helloservice-canary.sample-app-production.svc.cluster.local
    - destination:
        host: helloservice-primary.sample-app-production.svc.cluster.local
      weight: 100
